Repository ArkEcosystem/dotnet-crypto, pull requests merged in 2019-05, with the labels that each got.

#27 doc: update link to Ark documentation
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved

#35 chore: update contribution link
  .github/CONTRIBUTING.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#36 feat: support new vendorfield length
  ArkEcosystem.Crypto/Transactions/Transaction.cs
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#38 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task
